version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: api-laravel:latest
        container_name: api_laravel_container
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./storage:/var/www/storage
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        container_name: nginx_container
        ports:
            - "85:80"
        volumes:
            - ./:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        depends_on:
            - app

networks:
    laravel:
        driver: bridge
